### ISSUE TITLE
Maintainers?

### ISSUE THREAD

**Issue by dballance** [pierremrtn/state_machine_bloc#5]
Hi @Pierre2tm - any interest in having someone else take over as maintainers / publishers of this package? We've forked an are adding capabilities, and are happy to take over as maintainers if it makes sense. No pressure - just figured it would be worth asking!

**Comment by pierremrtn** [comment]
Hello @dballance !
Well, first, I'm quite surprised to see people using this package. I have unlisted it for a while since I'm still thinking about the overall concept and future directions.

I would be happy to discuss a possible ownership transfer. Can you give more details about the features you're planning to add?

I've taken a look at the commits you've made on the fork; they can definitely be incorporated into this project.

**Comment by HighLiuk** [comment]
Hey there @dballance @Pierre2tm I'm interested in this project and I'm willing to help if I can

**Comment by pierremrtn** [comment]
I'm starting working on this package again.
Thanks @dballance for the improvements you've made on your fork, I've integrated them into the project.

> Hey there @dballance @Pierre2tm I'm interested in this project and I'm willing to help if I can

Feel free to propose pr or new issues!
